#!/bin/bash

DIRA=$1
DIRB=$2

cd $DIRA
find . | sed "s%\^${DIRA}%%g" | sort > /tmp/fileA
cd ..
cd $DIRB 
find . | sed "s%\^${DIRB}%%g" | sort > /tmp/fileB

echo "files in both dirs are filtered by -3"
echo "--------------------------------------------"
echo "$DIRA"
echo "	$DIRB"
echo "--------------------------------------------"
comm <(cat /tmp/fileA) <(cat /tmp/fileB) -3

