#!/bin/bash

DIRA=/tmp/nix-unified
DIRB=/tmp/nix-autotools

find $DIRA | sed "s%${DIRA}%%g" | sort > /tmp/fileA
find $DIRB | sed "s%${DIRB}%%g" | sort > /tmp/fileB

echo "files in both dirs are filtered by -3"
echo "--------------------------------------------"
echo "$DIRA"
echo "	$DIRB"
echo "--------------------------------------------"
comm <(cat /tmp/fileA) <(cat /tmp/fileB) -3

