#!/bin/bash 

if [ "$1" == "cmake" ]; then
	toolchain=cmake
	src_url="/home/meli/Desktop/nix/nix-0.16-cmake/build"
fi
if [ "$1" ==  "autotools" ]; then
	toolchain=automake
	src_url="/home/meli/Desktop/nix/nix-0.16/"
fi

if [ "$toolchain"x == ""x ]; then
	echo "error, no argument given"
	exit
fi

mPREFIX=/tmp/nix-prefix

# clean
rm -Rf "${mPREFIX}"

# remove the nix profile
rm -Rf ~/.nix-defexpr
rm -Rf ~/.nix-profile

# store
find /nix/store -exec chmod 0700 {} +
rm -Rf /nix/store/*

# install the software
cd "$src_url"
make install

cd ${mPREFIX}
export PATH=${mPREFIX}/bin:$PATH

nix-channel --update
nix-env -i vim
nix-collect-garbage

nix-env -i zsh
nix-collect-garbage

ls -la ${mPREFIX}/state/nix/profiles/default/bin
ls -la ~/.nix-*
