#!/bin/bash -v
# helps to see compiler / linker stuff, just uncomment 
#export VERBOSE=1

#NIXPATH="/tmp/nix-prefix"
NIXPATH="/tmp/nix-prefix"

#clean
mkdir -p build
rm -Rf /tmp/nix-prefix


cd /home/meli/Desktop/nix/nix-0.16-cmake && rm -Rf build/* && rm -Rf /tmp/nix-cmake/* && cd build 

if [ $? -eq 0 ]; then
	cmake -DCMAKE_INSTALL_PREFIX:PATH="${NIXPATH}" -DOVERWRITE_DEFAULT_STORE_DIR=ON .. && make install | tee -a cmake_make_debug 
	if [ $? -eq 0 ]; then
	
		echo "=========== BEGIN list of runtime path adaptions of cmake's 'make install' ============"
		grep "Set runtime path of" cmake_make_debug 
		echo "=========== END   list of runtime path adaptions of cmake ============"
		
		echo "=========== checking if the nix-env binary can find it's libraries for ${NIXPATH}/bin/nix-env ==========="
		ldd ${NIXPATH}/bin/nix-env 
		
		echo "=========== let's see if all symlinks are in ${NIXPATH} ==========="
		ls -la ${NIXPATH}/state/nix/gcroots
		
		echo "=========== executing the installed binary, should output --help something, in ${NIXPATH} ==========="
		${NIXPATH}/bin/nix-env 2>&1 | tee -a exec_test | grep -e '--help' 
		if [ $? -eq 0 ]; then
			echo "success: ${NIXPATH}/bin/nix-env was executable"
		else
			echo "fail: ${NIXPATH}/bin/nix-env was NOT executable"
			cat exec_test
		fi
	fi
fi

mv $NIXPATH/* /tmp/nix-cmake-prefix
