'\" t
.\"     Title: nix-channel
.\"    Author: Eelco Dolstra
.\" Generator: DocBook XSL-NS Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: August 2010
.\"    Manual: Command Reference
.\"    Source: Nix 0.16
.\"  Language: English
.\"
.TH "NIX\-CHANNEL" "1" "August 2010" "Nix 0\&.16" "Command Reference"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nix-channel \- manage Nix channels
.SH "SYNOPSIS"
.HP \w'\fBnix\-channel\fR\ 'u
\fBnix\-channel\fR {\fB\-\-add\fR\ \fIurl\fR | \fB\-\-remove\fR\ \fIurl\fR | \fB\-\-list\fR | \fB\-\-update\fR}
.SH "DESCRIPTION"
.PP
A Nix channel is mechanism that allows you to automatically stay up\-to\-date with a set of pre\-built Nix expressions\&. A Nix channel is just a URL that points to a place that contains a set of Nix expressions, as well as a
\fBnix\-push\fR
manifest\&. See also
Section\ \&4.4, \(lqChannels\(rq\&.
.PP
This command has the following operations:
.PP
\fB\-\-add\fR \fIurl\fR
.RS 4
Adds
\fIurl\fR
to the list of subscribed channels\&.
.RE
.PP
\fB\-\-remove\fR \fIurl\fR
.RS 4
Removes
\fIurl\fR
from the list of subscribed channels\&.
.RE
.PP
\fB\-\-list\fR
.RS 4
Prints the URLs of all subscribed channels on standard output\&.
.RE
.PP
\fB\-\-update\fR
.RS 4
Downloads the Nix expressions of all subscribed channels, makes them the default for
\fBnix\-env\fR
operations (by symlinking them in the directory
~/\&.nix\-defexpr), and performs a
\fBnix\-pull\fR
on the manifests of all channels to make pre\-built binaries available\&.
.RE
.PP
Note that
\fB\-\-add\fR
and
\fB\-\-remove\fR
do not automatically perform an update\&.
.PP
The list of subscribed channels is stored in
~/\&.nix\-channels\&.
.PP
A channel consists of two elements: a bzipped Tar archive containing the Nix expressions, and a manifest created by
\fBnix\-push\fR\&. These must be stored under
\fIurl\fR/nixexprs\&.tar\&.bz2
and
\fIurl\fR/MANIFEST, respectively\&.
.SH "AUTHOR"
.PP
\fBEelco Dolstra\fR
.br
Delft University of Technology, Department of Software Technology
.RS 4
Author
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2004, 2005, 2006, 2007, 2008, 2009, 2010 Eelco Dolstra
.br
